### PR TITLE
Generic ModelViewSet and ReadOnlyModelViewSet introspection

### PR DESCRIPTION
**Pull request by tuffnatty**
This patch adds support for generic `ModelViewSet`/`ReadOnlyModelViewSet` introspection, eliminating the need to decorate (non-existent) viewset methods with `view_config`, e.g. that's what I had to do before:
```python
class MyViewSet(viewsets.ModelViewSet):
    ...
    serializer_class = MySerializer
    ...
    @view_config(response_serializer=MySerializer)
    def retrieve(self, *args, **kwargs):
        return super(MyViewSet, self).retrieve(*args, **kwargs)
```
I'm not sure if it fits well to your way of doing things, but it does the trick for me. Now the only thing I'm missing is a fix for #28.

### CODE REVIEW

**Comment by limdauto** [comment]
@tuffnatty Interesting. Thanks for the fix. Do you think it's more consistent to tweak the `view_config` to decorate the class instead? I'm up for merging as-is although minimal API is what I'm striving for here. I'd quite like to limit to one way of adding these metadata, which is through the use of `view_config`

**Comment by tuffnatty** [comment]
hmm, I haven't thought of decorating the class. Probably it's more consistent, but alas, it won't help much with DRYness:
```python
@view_config(response_serializer=MySerializer)
class MyViewSet(viewsets.ModelViewSet):
    ...
    serializer_class = MySerializer
    ...
```
I'm just used to the principle that everything that can be autodetected should be, from the Django admin through DRF and the late (?) `rest_framework_swagger` it worked this way.

**Comment by limdauto** [comment]
@tuffnatty yea you made a good point. Merging.

**Comment by tuffnatty** [comment]
Thanks!

**Comment by limdauto** [comment]
@tuffnatty FYI I found the bug for https://github.com/limdauto/drf_openapi/issues/28. It's in DRF itself. I have opened a PR over there. Hope it will get merge soon. In the mean team, instead of `ListField`, you can use `ListSerializer` instead.

**Comment by tuffnatty** [comment]
@limdauto Thanks! Actually, I don't use any `ListField`s (so it's not #28), but I am using `ListSerializer`s which are all rendered in the resulting OpenAPI spec as arrays of strings instead of arrays of their respective child data types.

**Comment by limdauto** [comment]
@tuffnatty Oh sorry for that. I was using ListField so I thought it was a problem. I have fixed it. It's building but if you try 0.9.6, this problem should be fixed. Let me know if there is anything else I can help with.

**Pull request merged**
